const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync('index.html', 'utf8');
const version = Number(html.match(/name="scholiphi-version" content="(\d)"/)[1]);
assert([2, 3, 4].includes(version));
const scripts = [...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)];
for (const [, attrs, code] of scripts) if (!/\bsrc=/.test(attrs)) new vm.Script(code);
assert(html.includes('id="ts-view"'));
assert.equal(html.includes('id="os-view"'), version >= 3);
assert.equal(html.includes('id="pr-view"'), version >= 4);
const excluded = version === 2 ? ['operating-system', 'pricing'] : version === 3 ? ['pricing'] : [];
for (const route of excluded) assert(!new RegExp('href="#' + route).test(html), 'Excluded route remains linked: ' + route);
const script = scripts.find(([, attrs]) => /id="vo-js"/.test(attrs))[2];
const start = script.indexOf('var A=') + 6, end = script.indexOf(';var aud=', start);
const audio = vm.runInNewContext('(' + script.slice(start, end) + ')');
assert(audio['ts-top']);
assert.equal(Object.keys(audio).some(k => k.startsWith('os-')), version >= 3);
assert(script.includes('function watchAudio()'));
assert(script.includes('function invalidate()'));
console.log('Version ' + version + ': included pages, excluded links, recordings, playback fixes, and script syntax passed');
