const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync('index.html', 'utf8');
const version = Number(html.match(/name="scholiphi-version" content="(\d)"/)[1]);
assert([2, 3, 4].includes(version));
const scripts = [...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)];
for (const [, attrs, code] of scripts) if (!/\bsrc=/.test(attrs)) new vm.Script(code);
assert(html.includes('id="ts-view"'));
assert.equal(html.includes('id="os-view"'), version >= 3);
assert.equal(html.includes('id="pr-view"'), version >= 4);
const excluded = version === 2 ? ['operating-system', 'pricing'] : version === 3 ? ['pricing'] : [];
excluded.push('live-demo');
assert(!html.includes('data-livedemo'));
assert(!html.includes('id="live-demo"'));
assert(!html.includes('id="ldm-js"'));
assert(html.includes('id="demo-modal"'));
assert(html.includes('id="demo-js"'));
for (const route of excluded) assert(!new RegExp('href="#' + route).test(html), 'Excluded route remains linked: ' + route);
for (const marker of ['id="vo-js"', 'id="vo-fab"', 'id="vo-launch"', 'id="vo-bar"', 'id="holo"', 'id="phstage"', 'id="phipoint"', 'data-phitour', '__phiAud', 'data:audio/']) assert(!html.includes(marker), 'Voice tour remains: ' + marker);
console.log('Version ' + version + ': included pages, excluded links, voice-tour removal, and script syntax passed');
